[package]
name = "rssc"
version = "0.1.0"
authors = ["Emily Crandall Fleischman <emilycf@mit.edu>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
lazy_static = "0.2.9"
regex = "0.2.1"
unicode_categories = "0.1.1"
unicode-normalization = "0.1.3"
