[package]
name = "rssc"
version = "0.1.0"
authors = ["Emily Crandall Fleischman <emilycf@mit.edu>"]
edition = "2018"

[dependencies]
lazy_static = "0.2.9"
radix_trie = "0.1"
regex = "0.2"
thiserror = "1.0.31"
unicode_categories = "0.1"
unicode-normalization = "0.1"
